angular.module('app', 
				['ngRoute', 
				 'ngMask',
				 'angular-bootstrap-select',
				 'ngDialog',
				 'ngStorage',
				 'app.factories',
				 'app.dashboard',
				 'app.empresa',
				 'app.usuario',
				 'app.marketing',
				 'app.header'
				]);